on:
  push:
    branches: [ main ]

jobs:
  Run-npm-install:
    name: npm install
    runs-on: self-hosted

    steps:
    - name: run
      run: |
        npm install
        npm run dev
        
    
